tower:
  position:
    x: 0.5
    y: -0.5
    z: 0.023
  layers:
    - repeat: 0
      blocks:
      - x: -0.06
        y: 0.0
        qx: 0.0
        qy: -0.7071
        qz: 0.0
        qw: 0.7071
      - x: 0.0
        y: 0.0
        qx: 0.0
        qy: -0.7071
        qz: 0.0
        qw: 0.7071
      - x: 0.06
        y: 0.0
        qx: 0.0
        qy: -0.7071
        qz: 0.0
        qw: 0.7071
    - repeat: 0
      blocks:
      - x: -0.03
        y: 0.0
        qx: 0.0
        qy: -0.7071
        qz: 0.0
        qw: 0.7071
      - x: 0.03
        y: 0.0
        qx: 0.0
        qy: -0.7071
        qz: 0.0
        qw: 0.7071
    - repeat: 0
      blocks:
      - x: 0.0
        y: 0.0
        qx: 0.0
        qy: -0.7071
        qz: 0.0
        qw: 0.7071